### PR TITLE
Updates ScanPointGenerator copy to match WIP generator changes

### PR DESCRIPTION
**Pull request by c-mita**

### CODE REVIEW

**Comment by c-mita** [comment]
It's probably best not to merge this, as the version hasn't been changed yet.

**Comment by gerring** [comment]
Hmm sciscofpy is needed in the jython part of this open source project soon to be contributed to eclipse. But scisoftpy is not currently in an open source project. Any intention to do this @PeterC-DLS  or @jonahkichwacoders ?

**Comment by PeterC-DLS** [comment]
It is open source!

**Comment by gerring** [comment]
@PeterC-DLS  are we talking random repo on github or IP checked?

**Comment by PeterC-DLS** [comment]
You should know as you put it there!

**Comment by gerring** [comment]
In that case it's not open source.

**Comment by PeterC-DLS** [comment]
I see that you are redefining what open source means for the rest of us!

**Pull request merged**
