### PR TITLE
Fix to services for p45-config

### PR DESCRIPTION
**Pull request by gerring**
http://jira.diamond.ac.uk/browse/DAQ-148

### CODE REVIEW

**Comment by colinpalmer** [comment]
just happened to have a look at this - you don't need to remove the static declaration from all the methods, they'll continue working just fine with the dynamic policy (there's no link at all between "static" as a method modifier and as an OSGi policy, they don't need to match)

**Comment by gerring** [comment]
OSGi warnings come in the log file for me with the static version and the
event service is missing from Services. Is it possible you have changed it
without checking it works?

Matt

**Comment by colinpalmer** [comment]
No, it's definitely worked for me in plenty of places. If you make a service optional and dynamic and it's not available when Equinox resolves your component, it logs a message about it but will then just inject the service later when it becomes available. I've never seen any difference in how Equinox treats static and instance methods, it'll happily use either.

**Comment by gerring** [comment]
ok

**Pull request merged**
