### PR TITLE
[I15_1-69] Adds AtomQueueProcessors

### PR DESCRIPTION
**Pull request by mtwharmby**
Adds TaskBean and SubTaskAtomProcessors - this completes the suite of processors needed for I15-1.

Signed-off-by: Michael Wharmby michael.wharmby@diamond.ac.uk

### CODE REVIEW

**Comment by gerring** [comment]
Sorry you will need to press the update branch button once the other changes are accepted.

**Comment by gerring** [comment]
Ok press the update button at your leisure

**Comment by mtwharmby** [comment]
I have just pressed the update button. Once it's done running the tests, could you merge this please? I've already updated it three times!

**Comment by mtwharmby** [comment]
Cheers! :-)

**Pull request merged**
